In [1]:
import datetime
from astropy.time import Time
from rubin_sim.data import get_baseline
from os.path import basename
import sqlite3
import pandas as pd
import numpy as np

In [2]:
db_file = get_baseline()
run_name = basename(db_file).replace('.db', '')
con = sqlite3.connect(db_file)
df = pd.read_sql('select * from observations;', con)
con.close()
# Convert to a numpy array
visits_array = df.to_records(index=False)



In [3]:
def mjd2dayobs(mjd, offset= -0.5):
    atime = Time(mjd + offset, format="mjd")
    ymd = atime.to_value("ymdhms")
    year_str = ymd["year"].astype(str)
    mo_str = np.char.zfill(ymd["month"].astype(str), 2)
    day_str = np.char.zfill(ymd["day"].astype(str), 2)
    dayobs_str = np.char.add( year_str, mo_str)
    dayobs_str = np.char.add(dayobs_str, day_str)
    return dayobs_str

In [4]:
mjd2dayobs(65320)



/Users/yoachim/anaconda3/envs/rubin_14/lib/python3.14/site-packages/erfa/core.py:133: ErfaWarning: ERFA function "d2dtf" yielded 1 of "dubious year (Note 5)"
  warn(f'ERFA function "{func_name}" yielded {wmsg}', ErfaWarning)


np.str_('20370918')

In [5]:
do = mjd2dayobs(visits_array["observationStartMJD"])

/Users/yoachim/anaconda3/envs/rubin_14/lib/python3.14/site-packages/erfa/core.py:133: ErfaWarning: ERFA function "d2dtf" yielded 1409394 of "dubious year (Note 5)"
  warn(f'ERFA function "{func_name}" yielded {wmsg}', ErfaWarning)


In [10]:
ack = do.astype(int)

In [11]:
ack

array([20251031, 20251031, 20251031, ..., 20351031, 20351031, 20351031],
      shape=(2048612,))

In [12]:
udo, do_indx = np.unique(do, return_index=True)

array([      0,     557,    1289, ..., 2048158, 2048338, 2048488],
      shape=(2772,))

array([      0,     557,    1289, ..., 2048158, 2048338, 2048488],
      shape=(2772,))

np.True_